# Learn Posture

use machine learning to recognize robot's posture (following the example in [scikit-learn-intro.ipynb](./scikit-learn-intro.ipynb) )

## 1. Data collection

We have colleceted data before, you need to add new data if you want to add new posture.

* the dateset are in *robot_pose_data* folder
* each file contains the data belongs to this posture, e.g. the data in *Back* file are collected when robot was in "Back" posture
* the data file can be load by ```pickle```, e.g. ```pickle.load(open('Back'))```, the data is a list of feature data
* the features (e.g. each row of the data) are ['LHipYawPitch', 'LHipRoll', 'LHipPitch', 'LKneePitch', 'RHipYawPitch', 'RHipRoll', 'RHipPitch', 'RKneePitch', 'AngleX', 'AngleY'], where 'AngleX' and 'AngleY' are body angle (e.g. ```Perception.imu```) and others are joint angles.

## 2. Data preprocessing

In [63]:
%pylab inline
import pickle
from os import listdir, path
import numpy as np
from sklearn import svm, metrics

ROBOT_POSE_DATA_DIR = 'robot_pose_data'

Populating the interactive namespace from numpy and matplotlib


In [64]:
classes = listdir(ROBOT_POSE_DATA_DIR)
print classes

['Stand', 'Sit', 'HeadBack', 'StandInit', 'Frog', 'Belly', 'Right', 'Back', 'Crouch', 'Knee', 'Left']


In [65]:
def load_pose_data(i):
    '''load pose data from file'''
    data = []
    target = []
    # YOUR CODE HERE
    
    filename = path.join(ROBOT_POSE_DATA_DIR, classes[i])
    data = pickle.load(open(filename))
    target = [i] * len(data)
    return data, target

In [66]:
# load all the data
all_data = []
all_target = []
for i in range(0, len(classes)):
    sol = load_pose_data(i)
    all_data.extend(sol[0])
    all_target.extend(sol[1])

print 'total number of data', len(all_data)

total number of data 222


In [67]:
# shuffule data
permutation = np.random.permutation(len(all_data))
n_training_data = int(len(all_data) * 0.7)
training_data_idx = permutation[:n_training_data]

## 3. Learn on training data

In scikit-learn, an estimator for classification is a Python object that implements the methods fit(X, y) and predict(T). An example of an estimator is the class sklearn.svm.SVC that implements support vector classification.

In [68]:
clf = svm.SVC(gamma=0.001, C=100.)

### learning

In [69]:
# YOUR CODE HERE
print n_training_data
print training_data_idx
training_data = []
training_target =[]
for i, idx in enumerate(training_data_idx):
    training_data.append(all_data[idx])
    training_target.append(all_target[idx])
    
clf.fit(training_data, training_target)

155
[ 32 144  66 207 115   2 163  84 190  11 148 158 113 189 133   5  71  19
  30   0  90 162 125  73 168 183 191  29 114 176 135 151  10 187  93  78
  12  26 173 179  35 166 192 145  44 109  60 159  55 104  69 177 140  20
 129  13  68  36 132 156 120   9 147  83 138  89  52 102 161 178 154  18
 106 160  50 208  21 204 212  92   3  37 107 171 211 174  99 186 214 194
  56   6 128  28  47  41 157 200 167  82  77 123  58  14 196  40 217 117
 110  23 175  85 213 101  67  15 108 121  75  45  94 182 172 130 112 209
 181 184  38 197  24  22 111 164 155  76  79 165  81  65 219 198  86 127
  46  34 218 201  91  87  96 195  62 149 216]


SVC(C=100.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

### predicting

In [70]:
clf.predict(all_data[-1:]), all_target[-1:]

(array([10]), [10])

In [71]:
def evaluate(expected, predicted):
    print("Classification report:\n%s\n" % metrics.classification_report(expected, predicted))

    print("Confusion matrix:\n%s" % metrics.confusion_matrix(expected, predicted))

In [72]:
expected = []
predicted = []
# YOUR CODE HERE
expected = all_target
predicted = clf.predict(all_data)

evaluate(expected, predicted)

Classification report:
             precision    recall  f1-score   support

          0       1.00      1.00      1.00        11
          1       1.00      1.00      1.00        26
          2       1.00      1.00      1.00        10
          3       1.00      1.00      1.00        52
          4       1.00      1.00      1.00        10
          5       1.00      1.00      1.00        19
          6       1.00      0.91      0.95        11
          7       1.00      1.00      1.00        23
          8       0.97      1.00      0.98        30
          9       1.00      1.00      1.00        10
         10       1.00      1.00      1.00        20

avg / total       1.00      1.00      1.00       222


Confusion matrix:
[[11  0  0  0  0  0  0  0  0  0  0]
 [ 0 26  0  0  0  0  0  0  0  0  0]
 [ 0  0 10  0  0  0  0  0  0  0  0]
 [ 0  0  0 52  0  0  0  0  0  0  0]
 [ 0  0  0  0 10  0  0  0  0  0  0]
 [ 0  0  0  0  0 19  0  0  0  0  0]
 [ 0  0  0  0  0  0 10  0  1  0  0]
 [ 0  0  0  0 

## 4. Evaluate on the test data

In [73]:
expected = []
predicted = []
# YOUR CODE HERE
expected = training_target
predicted = clf.predict(training_data)

evaluate(expected, predicted)

Classification report:
             precision    recall  f1-score   support

          0       1.00      1.00      1.00         7
          1       1.00      1.00      1.00        20
          2       1.00      1.00      1.00         7
          3       1.00      1.00      1.00        34
          4       1.00      1.00      1.00         7
          5       1.00      1.00      1.00        13
          6       1.00      0.86      0.92         7
          7       1.00      1.00      1.00        15
          8       0.96      1.00      0.98        25
          9       1.00      1.00      1.00         8
         10       1.00      1.00      1.00        12

avg / total       0.99      0.99      0.99       155


Confusion matrix:
[[ 7  0  0  0  0  0  0  0  0  0  0]
 [ 0 20  0  0  0  0  0  0  0  0  0]
 [ 0  0  7  0  0  0  0  0  0  0  0]
 [ 0  0  0 34  0  0  0  0  0  0  0]
 [ 0  0  0  0  7  0  0  0  0  0  0]
 [ 0  0  0  0  0 13  0  0  0  0  0]
 [ 0  0  0  0  0  0  6  0  1  0  0]
 [ 0  0  0  0 

## 5. Deploy to the real system

We can simple use `pickle` module to serialize the trained classifier.

In [74]:
import pickle
ROBOT_POSE_CLF = 'robot_pose.pkl'
pickle.dump(clf, open(ROBOT_POSE_CLF, 'w'))

Then, in the application we can load the trained classifier again.

In [75]:
clf2 = pickle.load(open(ROBOT_POSE_CLF))
clf2.predict(all_data[-1:]), all_target[-1:]

(array([10]), [10])

In [76]:
print clf2

SVC(C=100.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)
